export const soup1 = [
  {
    type: "source_component",
    source_component_id: "simple_resistor_0",
    name: "R1",
    supplier_part_numbers: {
      jlcpcb: ["C620660"],
    },
    ftype: "simple_resistor",
    resistance: "100k",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_resistor_0",
    schematic_component_id: "schematic_component_simple_resistor_0",
    rotation: 1.5707963267948966,
    size: {
      width: 1,
      height: 0.3,
    },
    center: {
      x: -3,
      y: 0.5,
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_0",
    source_component_id: "simple_resistor_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_0",
    source_port_id: "source_port_0",
    center: {
      x: -3,
      y: 0,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_resistor_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_0",
    source_port_id: "source_port_0",
    x: 8.245000000000001,
    y: 5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_1",
    source_component_id: "simple_resistor_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_1",
    source_port_id: "source_port_1",
    center: {
      x: -3,
      y: 1,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_resistor_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_1",
    source_port_id: "source_port_1",
    x: 11.754999999999999,
    y: 5,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    text: "R1",
    schematic_text_id: "schematic_text_0",
    schematic_component_id: "schematic_component_simple_resistor_0",
    anchor: "left",
    position: {
      x: -2.7,
      y: 0.29999999999999993,
    },
    rotation: 0,
  },
  {
    type: "schematic_text",
    text: "100k",
    schematic_text_id: "schematic_text_1",
    schematic_component_id: "schematic_component_simple_resistor_0",
    anchor: "left",
    position: {
      x: -2.7,
      y: 0.5,
    },
    rotation: 0,
  },
  {
    type: "pcb_component",
    source_component_id: "simple_resistor_0",
    pcb_component_id: "pcb_component_simple_resistor_0",
    layer: "top",
    center: {
      x: 10,
      y: 5,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    shape: "rect",
    x: 8.245000000000001,
    y: 5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_0",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_10",
    shape: "rect",
    x: 11.754999999999999,
    y: 5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_0",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_1",
  },
  {
    type: "source_component",
    source_component_id: "simple_resistor_1",
    name: "R2",
    supplier_part_numbers: {
      jlcpcb: ["C52444"],
    },
    ftype: "simple_resistor",
    resistance: "1k",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_resistor_1",
    schematic_component_id: "schematic_component_simple_resistor_1",
    rotation: 1.5707963267948966,
    size: {
      width: 1,
      height: 0.3,
    },
    center: {
      x: -3,
      y: -1,
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_2",
    source_component_id: "simple_resistor_1",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_2",
    source_port_id: "source_port_2",
    center: {
      x: -3,
      y: -1.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_resistor_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_2",
    source_port_id: "source_port_2",
    x: 8.245000000000001,
    y: -5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_3",
    source_component_id: "simple_resistor_1",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_3",
    source_port_id: "source_port_3",
    center: {
      x: -3,
      y: -0.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_resistor_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_3",
    source_port_id: "source_port_3",
    x: 11.754999999999999,
    y: -5,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    text: "R2",
    schematic_text_id: "schematic_text_2",
    schematic_component_id: "schematic_component_simple_resistor_1",
    anchor: "left",
    position: {
      x: -2.7,
      y: -1.2,
    },
    rotation: 0,
  },
  {
    type: "schematic_text",
    text: "1k",
    schematic_text_id: "schematic_text_3",
    schematic_component_id: "schematic_component_simple_resistor_1",
    anchor: "left",
    position: {
      x: -2.7,
      y: -1,
    },
    rotation: 0,
  },
  {
    type: "pcb_component",
    source_component_id: "simple_resistor_1",
    pcb_component_id: "pcb_component_simple_resistor_1",
    layer: "top",
    center: {
      x: 10,
      y: -5,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    shape: "rect",
    x: 8.245000000000001,
    y: -5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_1",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_2",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_11",
    shape: "rect",
    x: 11.754999999999999,
    y: -5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_1",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_3",
  },
  {
    type: "source_component",
    source_component_id: "simple_resistor_2",
    name: "R3",
    supplier_part_numbers: {
      jlcpcb: ["C3000591"],
    },
    ftype: "simple_resistor",
    resistance: "220",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_resistor_2",
    schematic_component_id: "schematic_component_simple_resistor_2",
    rotation: 1.5707963267948966,
    size: {
      width: 1,
      height: 0.3,
    },
    center: {
      x: 3,
      y: 2,
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_4",
    source_component_id: "simple_resistor_2",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_4",
    source_port_id: "source_port_4",
    center: {
      x: 3,
      y: 1.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_resistor_2",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_4",
    source_port_id: "source_port_4",
    x: 28.245,
    y: 5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_5",
    source_component_id: "simple_resistor_2",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_5",
    source_port_id: "source_port_5",
    center: {
      x: 3,
      y: 2.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_resistor_2",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_5",
    source_port_id: "source_port_5",
    x: 31.755,
    y: 5,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    text: "R3",
    schematic_text_id: "schematic_text_4",
    schematic_component_id: "schematic_component_simple_resistor_2",
    anchor: "left",
    position: {
      x: 3.3,
      y: 1.8,
    },
    rotation: 0,
  },
  {
    type: "schematic_text",
    text: "220",
    schematic_text_id: "schematic_text_5",
    schematic_component_id: "schematic_component_simple_resistor_2",
    anchor: "left",
    position: {
      x: 3.3,
      y: 2,
    },
    rotation: 0,
  },
  {
    type: "pcb_component",
    source_component_id: "simple_resistor_2",
    pcb_component_id: "pcb_component_simple_resistor_2",
    layer: "top",
    center: {
      x: 30,
      y: 5,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_4",
    shape: "rect",
    x: 28.245,
    y: 5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_2",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_12",
    shape: "rect",
    x: 31.755,
    y: 5,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_resistor_2",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_5",
  },
  {
    type: "source_component",
    source_component_id: "simple_capacitor_0",
    name: "C1",
    supplier_part_numbers: {
      jlcpcb: ["C92834"],
    },
    ftype: "simple_capacitor",
    capacitance: "10uF",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_capacitor_0",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    rotation: 1.5707963267948966,
    size: {
      width: 0.75,
      height: 0.75,
    },
    center: {
      x: -3,
      y: 2,
    },
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_6",
    source_component_id: "simple_capacitor_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_6",
    source_port_id: "source_port_6",
    center: {
      x: -3,
      y: 1.5,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_component_simple_capacitor_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_6",
    source_port_id: "source_port_6",
    x: 8.245000000000001,
    y: 10,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_7",
    source_component_id: "simple_capacitor_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_7",
    source_port_id: "source_port_7",
    center: {
      x: -3,
      y: 2.5,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_component_simple_capacitor_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_7",
    source_port_id: "source_port_7",
    x: 11.754999999999999,
    y: 10,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    text: "C1",
    schematic_text_id: "schematic_text_6",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    anchor: "left",
    position: {
      x: -2.7,
      y: 1.5,
    },
    rotation: 0,
  },
  {
    type: "schematic_text",
    text: "10uF",
    schematic_text_id: "schematic_text_7",
    schematic_component_id: "schematic_component_simple_capacitor_0",
    anchor: "left",
    position: {
      x: -2.7,
      y: 1.7,
    },
    rotation: 0,
  },
  {
    type: "pcb_component",
    source_component_id: "simple_capacitor_0",
    pcb_component_id: "pcb_component_simple_capacitor_0",
    layer: "top",
    center: {
      x: 10,
      y: 10,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_5",
    shape: "rect",
    x: 8.245000000000001,
    y: 10,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_capacitor_0",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_6",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_13",
    shape: "rect",
    x: 11.754999999999999,
    y: 10,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_component_simple_capacitor_0",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_7",
  },
  {
    type: "source_component",
    source_component_id: "simple_diode_0",
    name: "LED",
    ftype: "simple_diode",
    supplier_part_numbers: {
      jlcpcb: ["C965841"],
    },
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_simple_diode_component_0",
    source_component_id: "simple_diode_0",
    center: {
      x: 3,
      y: 0.5,
    },
    rotation: 1.5707963267948966,
    size: {
      width: 0.45899999999999963,
      height: 1,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_diode_0",
    pcb_component_id: "pcb_simple_diode_component_0",
    layer: "top",
    center: {
      x: 30,
      y: 0,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_14",
    shape: "rect",
    x: 28.245,
    y: 0,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_simple_diode_component_0",
    port_hints: ["left", "1"],
    pcb_port_id: "pcb_port_8",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_21",
    shape: "rect",
    x: 31.755,
    y: 0,
    width: 1.27,
    height: 2.06,
    layer: "top",
    pcb_component_id: "pcb_simple_diode_component_0",
    port_hints: ["right", "2"],
    pcb_port_id: "pcb_port_9",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_8",
    source_port_id: "source_port_8",
    center: {
      x: 3,
      y: 0,
    },
    facing_direction: "up",
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_9",
    source_port_id: "source_port_9",
    center: {
      x: 3,
      y: 1,
    },
    facing_direction: "down",
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 3,
    y1: 0,
    x2: 3,
    y2: 0.3443,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 3,
    y1: 0.8033,
    x2: 3,
    y2: 1,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 3,
    y1: 0.8033,
    x2: 2.7705,
    y2: 0.34430000000000005,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 2.7705,
    y1: 0.34430000000000005,
    x2: 3.2295,
    y2: 0.34429999999999994,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 3.2295,
    y1: 0.34429999999999994,
    x2: 3,
    y2: 0.8033,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    drawing_type: "line",
    type: "schematic_line",
    x1: 3.2295,
    y1: 0.8033,
    x2: 2.7705,
    y2: 0.8033,
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: 3.25,
      y: 0.5,
    },
    text: "LED",
    schematic_component_id: "schematic_simple_diode_component_0",
  },
  {
    type: "source_port",
    name: "left",
    source_port_id: "source_port_8",
    source_component_id: "simple_diode_0",
    pin_number: 1,
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_8",
    source_port_id: "source_port_8",
    x: 28.245,
    y: 0,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "right",
    source_port_id: "source_port_9",
    source_component_id: "simple_diode_0",
    pin_number: 2,
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_9",
    source_port_id: "source_port_9",
    x: 31.755,
    y: 0,
    layers: ["top"],
  },
  {
    type: "source_component",
    source_component_id: "simple_bug_0",
    name: "U1",
    supplier_part_numbers: {
      jlcpcb: ["C596355"],
    },
    ftype: "simple_bug",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_bug_0",
    schematic_component_id: "schematic_component_simple_bug_0",
    rotation: 0,
    size: {
      width: 1,
      height: 2.5,
    },
    center: {
      x: 0,
      y: 0,
    },
    port_arrangement: {
      left_side: {
        pins: [6, 7, 2],
      },
      right_side: {
        pins: [8, 4, 3, 5, 1],
      },
    },
    port_labels: {
      "1": "GND",
      "2": "TRIG",
      "3": "OUT",
      "4": "RESET",
      "5": "CTRL",
      "6": "THRES",
      "7": "DISCH",
      "8": "VCC",
    },
  },
  {
    type: "source_port",
    name: "THRES",
    source_port_id: "source_port_10",
    source_component_id: "simple_bug_0",
    pin_number: 6,
    port_hints: ["THRES", "6"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_10",
    source_port_id: "source_port_10",
    center: {
      x: -0.75,
      y: -0.5,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_10",
    schematic_text_id: "schematic_text_16",
    text: "6",
    anchor: "center",
    rotation: 0,
    position: {
      x: -0.6262563132923542,
      y: -0.6237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_10",
    source_port_id: "source_port_10",
    x: 22.75,
    y: 0.635,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "DISCH",
    source_port_id: "source_port_11",
    source_component_id: "simple_bug_0",
    pin_number: 7,
    port_hints: ["DISCH", "7"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_11",
    source_port_id: "source_port_11",
    center: {
      x: -0.75,
      y: 0,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_11",
    schematic_text_id: "schematic_text_17",
    text: "7",
    anchor: "center",
    rotation: 0,
    position: {
      x: -0.6262563132923542,
      y: -0.12374368670764582,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_11",
    source_port_id: "source_port_11",
    x: 22.75,
    y: -0.635,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "TRIG",
    source_port_id: "source_port_12",
    source_component_id: "simple_bug_0",
    pin_number: 2,
    port_hints: ["TRIG", "2"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_12",
    source_port_id: "source_port_12",
    center: {
      x: -0.75,
      y: 0.5,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_12",
    schematic_text_id: "schematic_text_18",
    text: "2",
    anchor: "center",
    rotation: 0,
    position: {
      x: -0.6262563132923542,
      y: 0.3762563132923542,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_12",
    source_port_id: "source_port_12",
    x: 17.25,
    y: -0.635,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "VCC",
    source_port_id: "source_port_13",
    source_component_id: "simple_bug_0",
    pin_number: 8,
    port_hints: ["VCC", "8"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_13",
    source_port_id: "source_port_13",
    center: {
      x: 0.75,
      y: -1,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_13",
    schematic_text_id: "schematic_text_19",
    text: "8",
    anchor: "center",
    rotation: 0,
    position: {
      x: 0.6262563132923542,
      y: -1.1237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_13",
    source_port_id: "source_port_13",
    x: 22.75,
    y: -1.905,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "RESET",
    source_port_id: "source_port_14",
    source_component_id: "simple_bug_0",
    pin_number: 4,
    port_hints: ["RESET", "4"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_14",
    source_port_id: "source_port_14",
    center: {
      x: 0.75,
      y: -0.5,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_14",
    schematic_text_id: "schematic_text_20",
    text: "4",
    anchor: "center",
    rotation: 0,
    position: {
      x: 0.6262563132923542,
      y: -0.6237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_14",
    source_port_id: "source_port_14",
    x: 17.25,
    y: 1.905,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "OUT",
    source_port_id: "source_port_15",
    source_component_id: "simple_bug_0",
    pin_number: 3,
    port_hints: ["OUT", "3"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_15",
    source_port_id: "source_port_15",
    center: {
      x: 0.75,
      y: 0,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_15",
    schematic_text_id: "schematic_text_21",
    text: "3",
    anchor: "center",
    rotation: 0,
    position: {
      x: 0.6262563132923542,
      y: -0.12374368670764582,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_15",
    source_port_id: "source_port_15",
    x: 17.25,
    y: 0.635,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "CTRL",
    source_port_id: "source_port_16",
    source_component_id: "simple_bug_0",
    pin_number: 5,
    port_hints: ["CTRL", "5"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_16",
    source_port_id: "source_port_16",
    center: {
      x: 0.75,
      y: 0.5,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_16",
    schematic_text_id: "schematic_text_22",
    text: "5",
    anchor: "center",
    rotation: 0,
    position: {
      x: 0.6262563132923542,
      y: 0.3762563132923542,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_16",
    source_port_id: "source_port_16",
    x: 22.75,
    y: 1.905,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "GND",
    source_port_id: "source_port_17",
    source_component_id: "simple_bug_0",
    pin_number: 1,
    port_hints: ["GND", "1"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_17",
    source_port_id: "source_port_17",
    center: {
      x: 0.75,
      y: 1,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_17",
    schematic_text_id: "schematic_text_23",
    text: "1",
    anchor: "center",
    rotation: 0,
    position: {
      x: 0.6262563132923542,
      y: 0.8762563132923542,
    },
    schematic_component_id: "schematic_component_simple_bug_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_17",
    source_port_id: "source_port_17",
    x: 17.25,
    y: -1.905,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_8",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "THRES",
    anchor: "left",
    rotation: 0,
    position: {
      x: -0.35,
      y: -0.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_9",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "DISCH",
    anchor: "left",
    rotation: 0,
    position: {
      x: -0.35,
      y: 0,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_10",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "TRIG",
    anchor: "left",
    rotation: 0,
    position: {
      x: -0.35,
      y: 0.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_11",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "VCC",
    anchor: "right",
    rotation: 0,
    position: {
      x: 0.35,
      y: -1,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_12",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "RESET",
    anchor: "right",
    rotation: 0,
    position: {
      x: 0.35,
      y: -0.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_13",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "OUT",
    anchor: "right",
    rotation: 0,
    position: {
      x: 0.35,
      y: 0,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_14",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "CTRL",
    anchor: "right",
    rotation: 0,
    position: {
      x: 0.35,
      y: 0.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_15",
    schematic_component_id: "schematic_component_simple_bug_0",
    text: "GND",
    anchor: "right",
    rotation: 0,
    position: {
      x: 0.35,
      y: 1,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_bug_0",
    pcb_component_id: "pcb_component_simple_bug_0",
    layer: "top",
    center: {
      x: 20,
      y: 0,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_6",
    shape: "rect",
    x: 17.25,
    y: -1.905,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["1"],
    pcb_port_id: "pcb_port_17",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_15",
    shape: "rect",
    x: 17.25,
    y: -0.635,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["2"],
    pcb_port_id: "pcb_port_12",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_22",
    shape: "rect",
    x: 17.25,
    y: 0.635,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["3"],
    pcb_port_id: "pcb_port_15",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_28",
    shape: "rect",
    x: 17.25,
    y: 1.905,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["4"],
    pcb_port_id: "pcb_port_14",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_32",
    shape: "rect",
    x: 22.75,
    y: 1.905,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["5"],
    pcb_port_id: "pcb_port_16",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_35",
    shape: "rect",
    x: 22.75,
    y: 0.635,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["6"],
    pcb_port_id: "pcb_port_10",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_38",
    shape: "rect",
    x: 22.75,
    y: -0.635,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["7"],
    pcb_port_id: "pcb_port_11",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_39",
    shape: "rect",
    x: 22.75,
    y: -1.905,
    width: 1,
    height: 0.5,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_0",
    port_hints: ["8"],
    pcb_port_id: "pcb_port_13",
  },
  {
    type: "source_component",
    source_component_id: "generic_0",
    name: "B1",
    supplier_part_numbers: {
      jlcpcb: ["C70377"],
    },
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_generic_component_0",
    source_component_id: "generic_0",
    center: {
      x: -1.5,
      y: -3,
    },
    rotation: 0,
    size: {
      width: 2,
      height: 0.5,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "generic_0",
    pcb_component_id: "pcb_generic_component_0",
    layer: "top",
    center: {
      x: -30,
      y: 30,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_16",
    shape: "rect",
    x: -30,
    y: 15.5,
    width: 4.2,
    height: 3,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["pos"],
    pcb_port_id: "pcb_port_19",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_23",
    shape: "rect",
    x: -30,
    y: 44.5,
    width: 4.2,
    height: 3,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["neg"],
    pcb_port_id: "pcb_port_18",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_18",
    source_port_id: "source_port_18",
    center: {
      x: -2,
      y: -3,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_19",
    source_port_id: "source_port_19",
    center: {
      x: -1,
      y: -3,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    drawing_type: "box",
    type: "schematic_box",
    width: 2,
    height: 0.5,
    x: -1.5,
    y: -3,
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: -1.5,
      y: -3,
    },
    text: "B1",
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: -1.75,
      y: -3.125,
    },
    text: "-",
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: -1.25,
      y: -3.125,
    },
    text: "+",
    schematic_component_id: "schematic_generic_component_0",
  },
  {
    type: "source_port",
    name: "neg",
    source_port_id: "source_port_18",
    source_component_id: "generic_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_18",
    source_port_id: "source_port_18",
    x: -30,
    y: 44.5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "pos",
    source_port_id: "source_port_19",
    source_component_id: "generic_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_19",
    source_port_id: "source_port_19",
    x: -30,
    y: 15.5,
    layers: ["top"],
  },
  {
    type: "source_component",
    source_component_id: "generic_1",
    name: "B2",
    supplier_part_numbers: {
      jlcpcb: ["C70377"],
    },
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_generic_component_1",
    source_component_id: "generic_1",
    center: {
      x: 1.5,
      y: -3,
    },
    rotation: 0,
    size: {
      width: 2,
      height: 0.5,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "generic_1",
    pcb_component_id: "pcb_generic_component_1",
    layer: "top",
    center: {
      x: -30,
      y: -30,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_17",
    shape: "rect",
    x: -30,
    y: -44.5,
    width: 4.2,
    height: 3,
    layer: "top",
    pcb_component_id: "pcb_generic_component_1",
    port_hints: ["pos"],
    pcb_port_id: "pcb_port_21",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_24",
    shape: "rect",
    x: -30,
    y: -15.5,
    width: 4.2,
    height: 3,
    layer: "top",
    pcb_component_id: "pcb_generic_component_1",
    port_hints: ["neg"],
    pcb_port_id: "pcb_port_20",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_20",
    source_port_id: "source_port_20",
    center: {
      x: 1,
      y: -3,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_21",
    source_port_id: "source_port_21",
    center: {
      x: 2,
      y: -3,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    drawing_type: "box",
    type: "schematic_box",
    width: 2,
    height: 0.5,
    x: 1.5,
    y: -3,
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: 1.5,
      y: -3,
    },
    text: "B2",
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: 1.25,
      y: -3.125,
    },
    text: "-",
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    anchor: "center",
    type: "schematic_text",
    position: {
      x: 1.75,
      y: -3.125,
    },
    text: "+",
    schematic_component_id: "schematic_generic_component_1",
  },
  {
    type: "source_port",
    name: "neg",
    source_port_id: "source_port_20",
    source_component_id: "generic_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_20",
    source_port_id: "source_port_20",
    x: -30,
    y: -15.5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "pos",
    source_port_id: "source_port_21",
    source_component_id: "generic_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_21",
    source_port_id: "source_port_21",
    x: -30,
    y: -44.5,
    layers: ["top"],
  },
  {
    type: "source_component",
    source_component_id: "simple_bug_1",
    name: "S1",
    supplier_part_numbers: {
      jlcpcb: ["C2906280"],
    },
    ftype: "simple_bug",
  },
  {
    type: "schematic_component",
    source_component_id: "simple_bug_1",
    schematic_component_id: "schematic_component_simple_bug_1",
    rotation: 0,
    size: {
      width: 1,
      height: 1.5,
    },
    center: {
      x: 4,
      y: -1.5,
    },
    port_arrangement: {
      left_size: 3,
      right_size: 3,
    },
    port_labels: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
    },
  },
  {
    type: "source_port",
    name: "1",
    source_port_id: "source_port_22",
    source_component_id: "simple_bug_1",
    pin_number: 1,
    port_hints: ["1", "1"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_22",
    source_port_id: "source_port_22",
    center: {
      x: 3.25,
      y: -2,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_22",
    schematic_text_id: "schematic_text_30",
    text: "1",
    anchor: "center",
    rotation: 0,
    position: {
      x: 3.3737436867076456,
      y: -2.1237436867076456,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_22",
    source_port_id: "source_port_22",
    x: -2.25,
    y: -22.5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "2",
    source_port_id: "source_port_23",
    source_component_id: "simple_bug_1",
    pin_number: 2,
    port_hints: ["2", "2"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_23",
    source_port_id: "source_port_23",
    center: {
      x: 3.25,
      y: -1.5,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_23",
    schematic_text_id: "schematic_text_31",
    text: "2",
    anchor: "center",
    rotation: 0,
    position: {
      x: 3.3737436867076456,
      y: -1.6237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_23",
    source_port_id: "source_port_23",
    x: -2.25,
    y: -20,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "3",
    source_port_id: "source_port_24",
    source_component_id: "simple_bug_1",
    pin_number: 3,
    port_hints: ["3", "3"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_24",
    source_port_id: "source_port_24",
    center: {
      x: 3.25,
      y: -1,
    },
    facing_direction: "left",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_24",
    schematic_text_id: "schematic_text_32",
    text: "3",
    anchor: "center",
    rotation: 0,
    position: {
      x: 3.3737436867076456,
      y: -1.1237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_24",
    source_port_id: "source_port_24",
    x: -2.25,
    y: -17.5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "4",
    source_port_id: "source_port_25",
    source_component_id: "simple_bug_1",
    pin_number: 4,
    port_hints: ["4", "4"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_25",
    source_port_id: "source_port_25",
    center: {
      x: 4.75,
      y: -2,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_25",
    schematic_text_id: "schematic_text_33",
    text: "4",
    anchor: "center",
    rotation: 0,
    position: {
      x: 4.626256313292354,
      y: -2.1237436867076456,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_25",
    source_port_id: "source_port_25",
    x: 2.25,
    y: -17.5,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "5",
    source_port_id: "source_port_26",
    source_component_id: "simple_bug_1",
    pin_number: 5,
    port_hints: ["5", "5"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_26",
    source_port_id: "source_port_26",
    center: {
      x: 4.75,
      y: -1.5,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_26",
    schematic_text_id: "schematic_text_34",
    text: "5",
    anchor: "center",
    rotation: 0,
    position: {
      x: 4.626256313292354,
      y: -1.6237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_26",
    source_port_id: "source_port_26",
    x: 2.25,
    y: -20,
    layers: ["top"],
  },
  {
    type: "source_port",
    name: "6",
    source_port_id: "source_port_27",
    source_component_id: "simple_bug_1",
    pin_number: 6,
    port_hints: ["6", "6"],
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_27",
    source_port_id: "source_port_27",
    center: {
      x: 4.75,
      y: -1,
    },
    facing_direction: "right",
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "schematic_text",
    schematic_port_id: "schematic_port_27",
    schematic_text_id: "schematic_text_35",
    text: "6",
    anchor: "center",
    rotation: 0,
    position: {
      x: 4.626256313292354,
      y: -1.1237436867076458,
    },
    schematic_component_id: "schematic_component_simple_bug_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_27",
    source_port_id: "source_port_27",
    x: 2.25,
    y: -22.5,
    layers: ["top"],
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_24",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "1",
    anchor: "left",
    rotation: 0,
    position: {
      x: 3.65,
      y: -2,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_25",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "2",
    anchor: "left",
    rotation: 0,
    position: {
      x: 3.65,
      y: -1.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_26",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "3",
    anchor: "left",
    rotation: 0,
    position: {
      x: 3.65,
      y: -1,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_27",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "4",
    anchor: "right",
    rotation: 0,
    position: {
      x: 4.35,
      y: -2,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_28",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "5",
    anchor: "right",
    rotation: 0,
    position: {
      x: 4.35,
      y: -1.5,
    },
  },
  {
    type: "schematic_text",
    schematic_text_id: "schematic_text_29",
    schematic_component_id: "schematic_component_simple_bug_1",
    text: "6",
    anchor: "right",
    rotation: 0,
    position: {
      x: 4.35,
      y: -1,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "simple_bug_1",
    pcb_component_id: "pcb_component_simple_bug_1",
    layer: "top",
    center: {
      x: 0,
      y: -20,
    },
    rotation: 0,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_7",
    shape: "rect",
    x: -2.25,
    y: -22.5,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["1"],
    pcb_port_id: "pcb_port_22",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_18",
    shape: "rect",
    x: -2.25,
    y: -20,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["2"],
    pcb_port_id: "pcb_port_23",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_25",
    shape: "rect",
    x: -2.25,
    y: -17.5,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["3"],
    pcb_port_id: "pcb_port_24",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_29",
    shape: "rect",
    x: 2.25,
    y: -17.5,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["4"],
    pcb_port_id: "pcb_port_25",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_33",
    shape: "rect",
    x: 2.25,
    y: -20,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["5"],
    pcb_port_id: "pcb_port_26",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_36",
    shape: "rect",
    x: 2.25,
    y: -22.5,
    width: 2,
    height: 1,
    layer: "top",
    pcb_component_id: "pcb_component_simple_bug_1",
    port_hints: ["6"],
    pcb_port_id: "pcb_port_27",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: ["source_port_19", "source_port_20"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_0",
    schematic_trace_id: "schematic_trace_0",
    edges: [
      {
        from: {
          x: -1,
          y: -2.6,
        },
        to: {
          x: 1,
          y: -2.6,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_0",
    source_trace_id: "source_trace_0",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 1,
        x: -30,
        y: 15.600000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 1,
        x: -30,
        y: -15,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 1,
        x: -30,
        y: 15.999999999999996,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 1,
        x: -30,
        y: -15.400000000000002,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_1",
    connected_source_port_ids: ["source_port_11", "source_port_3"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_1",
    schematic_trace_id: "schematic_trace_1",
    edges: [
      {
        from: {
          x: -0.6999999999999997,
          y: 0,
        },
        to: {
          x: -0.6999999999999997,
          y: -0.19999999999999996,
        },
      },
      {
        from: {
          x: -0.6999999999999997,
          y: -0.19999999999999996,
        },
        to: {
          x: -2.4,
          y: -0.19999999999999996,
        },
      },
      {
        from: {
          x: -2.4,
          y: -0.19999999999999996,
        },
        to: {
          x: -2.4,
          y: -0.5,
        },
      },
      {
        from: {
          x: -2.4,
          y: -0.5,
        },
        to: {
          x: -3,
          y: -0.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_1",
    source_trace_id: "source_trace_1",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.8,
        y: -5,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 13,
        y: -5,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 13.200000000000001,
        y: -4.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 13.200000000000001,
        y: -4.800000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 13.600000000000001,
        y: -4.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14,
        y: -4.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14.400000000000002,
        y: -4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14.8,
        y: -4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.600000000000001,
        y: -3.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.200000000000003,
        y: -3.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.6,
        y: -2.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 19.6,
        y: -2.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 21.200000000000003,
        y: -1.2000000000000002,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 21.6,
        y: -1.2000000000000002,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22.6,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22.8,
        y: -0.6000000000000005,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_2",
    connected_source_port_ids: ["source_port_3", "source_port_0"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_2",
    schematic_trace_id: "schematic_trace_2",
    edges: [
      {
        from: {
          x: -3,
          y: 0,
        },
        to: {
          x: -3,
          y: -0.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_2",
    source_trace_id: "source_trace_2",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: 5,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: 4.200000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 3.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.600000000000001,
        y: 3.6000000000000014,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.600000000000001,
        y: 3,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.8,
        y: 2.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.8,
        y: -1,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.600000000000001,
        y: -3.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.600000000000001,
        y: -4.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.8,
        y: -5,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_3",
    connected_source_port_ids: ["source_port_1", "source_port_6"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_3",
    schematic_trace_id: "schematic_trace_3",
    edges: [
      {
        from: {
          x: -3,
          y: 1,
        },
        to: {
          x: -3,
          y: 1.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_3",
    source_trace_id: "source_trace_3",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.8,
        y: 5,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10.4,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10.4,
        y: 6.800000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10,
        y: 7.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10,
        y: 7.6000000000000005,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.600000000000001,
        y: 9,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.600000000000001,
        y: 9.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 9.6,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 9.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: 10,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_4",
    connected_source_port_ids: ["source_port_10", "source_port_6"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_4",
    schematic_trace_id: "schematic_trace_4",
    edges: [
      {
        from: {
          x: -0.6999999999999997,
          y: -0.5,
        },
        to: {
          x: -1.7999999999999998,
          y: -0.5,
        },
      },
      {
        from: {
          x: -1.7999999999999998,
          y: -0.5,
        },
        to: {
          x: -1.7999999999999998,
          y: 1.5,
        },
      },
      {
        from: {
          x: -1.7999999999999998,
          y: 1.5,
        },
        to: {
          x: -3,
          y: 1.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_4",
    source_trace_id: "source_trace_4",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10.4,
        y: 8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10.4,
        y: 8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12.4,
        y: 8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 13.200000000000001,
        y: 7.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.200000000000001,
        y: 7.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 21.6,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 21.6,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22.6,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22.8,
        y: 0.5999999999999996,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_5",
    connected_source_port_ids: ["source_port_12", "source_port_6"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_5",
    schematic_trace_id: "schematic_trace_5",
    edges: [
      {
        from: {
          x: -0.6999999999999997,
          y: 0.5,
        },
        to: {
          x: -0.6999999999999997,
          y: 1.2000000000000002,
        },
      },
      {
        from: {
          x: -0.6999999999999997,
          y: 1.2000000000000002,
        },
        to: {
          x: -3,
          y: 1.2000000000000002,
        },
      },
      {
        from: {
          x: -3,
          y: 1.2000000000000002,
        },
        to: {
          x: -3,
          y: 1.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_5",
    source_trace_id: "source_trace_5",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.4,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12.8,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12.8,
        y: 4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.600000000000001,
        y: 1.1999999999999993,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.600000000000001,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16,
        y: 0.39999999999999947,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16,
        y: -0.40000000000000036,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16.4,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16.4,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17,
        y: -0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.200000000000003,
        y: -0.6000000000000005,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_6",
    connected_source_port_ids: ["source_port_7", "source_port_18"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_6",
    schematic_trace_id: "schematic_trace_6",
    edges: [
      {
        from: {
          x: -3,
          y: 2.5,
        },
        to: {
          x: -3,
          y: 3,
        },
      },
      {
        from: {
          x: -3,
          y: 3,
        },
        to: {
          x: -4,
          y: 3,
        },
      },
      {
        from: {
          x: -4,
          y: 3,
        },
        to: {
          x: -4,
          y: -3,
        },
      },
      {
        from: {
          x: -2,
          y: -2.5999999999999996,
        },
        to: {
          x: -2,
          y: -2.7,
        },
      },
      {
        from: {
          x: -2,
          y: -2.7,
        },
        to: {
          x: -2.8,
          y: -2.7,
        },
      },
      {
        from: {
          x: -2.8,
          y: -2.7,
        },
        to: {
          x: -2.8,
          y: -3,
        },
      },
      {
        from: {
          x: -2.8,
          y: -3,
        },
        to: {
          x: -4,
          y: -3,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_14",
    source_trace_id: "source_trace_6",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 11.8,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 11.200000000000001,
        y: 10.600000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 11.200000000000001,
        y: 10.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 10,
        y: 12,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 10,
        y: 12.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 4.4,
        y: 17.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 4.2,
        y: 17.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 4,
        y: 18,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 4,
        y: 18,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: 1,
        y: 18,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -5,
        y: 24,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -7,
        y: 24,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -10,
        y: 27,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -12,
        y: 27,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -12,
        y: 27,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -16.2,
        y: 31.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -16.599999999999998,
        y: 31.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -30,
        y: 44.6,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_7",
    connected_source_port_ids: ["source_port_17", "source_port_7"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_7",
    schematic_trace_id: "schematic_trace_7",
    edges: [
      {
        from: {
          x: 0.8000000000000007,
          y: 1,
        },
        to: {
          x: 0.8000000000000007,
          y: 2.5,
        },
      },
      {
        from: {
          x: 0.8000000000000007,
          y: 2.5,
        },
        to: {
          x: -3,
          y: 2.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_6",
    source_trace_id: "source_trace_7",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.2,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 14,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 14,
        y: 12,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 14,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 14,
        y: 12,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14,
        y: 12,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.8,
        y: 10,
      },
    ],
  },
  {
    type: "pcb_via",
    x: 14,
    y: -2,
    from_layer: "top",
    to_layer: "bottom",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "pcb_via",
    x: 14,
    y: 12,
    from_layer: "bottom",
    to_layer: "top",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_8",
    connected_source_port_ids: ["source_port_5", "source_port_7"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_8",
    schematic_trace_id: "schematic_trace_8",
    edges: [
      {
        from: {
          x: 3,
          y: 2.5,
        },
        to: {
          x: -3,
          y: 2.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_7",
    source_trace_id: "source_trace_8",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 11.8,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12.8,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 12.8,
        y: 10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14,
        y: 8.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 23.6,
        y: 8.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 26.000000000000004,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 29.200000000000003,
        y: 6.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 30.400000000000002,
        y: 5.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.200000000000003,
        y: 5.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.200000000000003,
        y: 5.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.6,
        y: 5.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.800000000000004,
        y: 5,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_9",
    connected_source_port_ids: ["source_port_9", "source_port_4"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_9",
    schematic_trace_id: "schematic_trace_9",
    edges: [
      {
        from: {
          x: 3,
          y: 1.1,
        },
        to: {
          x: 3,
          y: 1.5000000000000002,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_8",
    source_trace_id: "source_trace_9",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 28.200000000000003,
        y: 5,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 29.200000000000003,
        y: 4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 29.200000000000003,
        y: 3.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.200000000000003,
        y: 1.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.200000000000003,
        y: 1.6000000000000005,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.400000000000002,
        y: 1.4000000000000004,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.400000000000002,
        y: 1.2000000000000002,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.6,
        y: 1,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.6,
        y: 0.20000000000000018,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 31.800000000000004,
        y: 0,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_10",
    connected_source_port_ids: ["source_port_15", "source_port_8"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_10",
    schematic_trace_id: "schematic_trace_10",
    edges: [
      {
        from: {
          x: 0.7,
          y: 0,
        },
        to: {
          x: 0.7,
          y: -0.10000000000000009,
        },
      },
      {
        from: {
          x: 0.7,
          y: -0.10000000000000009,
        },
        to: {
          x: 3,
          y: -0.10000000000000009,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_9",
    source_trace_id: "source_trace_10",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.200000000000003,
        y: 0.5999999999999996,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.6,
        y: 0.5999999999999996,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.8,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 18.200000000000003,
        y: 0.7999999999999998,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 18.400000000000002,
        y: 1,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 19,
        y: 1,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 19,
        y: 1,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 19.6,
        y: 1,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 19.8,
        y: 0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 23.8,
        y: 0.8000000000000007,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 24,
        y: 0.6000000000000005,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 24.200000000000003,
        y: 0.6000000000000005,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 24.6,
        y: 0.20000000000000018,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 25.8,
        y: 0.20000000000000018,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 26,
        y: 0,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 26,
        y: 0,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 28.2,
        y: 0,
      },
    ],
  },
  {
    type: "pcb_via",
    x: 19,
    y: 1,
    from_layer: "top",
    to_layer: "bottom",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "pcb_via",
    x: 26,
    y: 0,
    from_layer: "bottom",
    to_layer: "top",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_11",
    connected_source_port_ids: ["source_port_14", "source_port_24"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_11",
    schematic_trace_id: "schematic_trace_11",
    edges: [
      {
        from: {
          x: 0.7,
          y: -0.5,
        },
        to: {
          x: 2.3,
          y: -0.5,
        },
      },
      {
        from: {
          x: 2.3,
          y: -0.5,
        },
        to: {
          x: 2.3,
          y: -1,
        },
      },
      {
        from: {
          x: 2.3,
          y: -1,
        },
        to: {
          x: 3.3,
          y: -1,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_10",
    source_trace_id: "source_trace_11",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 17.2,
        y: 2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16.2,
        y: 3,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16,
        y: 3,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 16,
        y: 3,
      },
      {
        route_type: "wire",
        layer: "bottom",
        width: 0.2,
        x: 16,
        y: -6,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 16,
        y: -6,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.600000000000001,
        y: -6,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 15.6,
        y: -6,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 14.4,
        y: -7.200000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10.4,
        y: -7.200000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 7.6,
        y: -10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 5.6,
        y: -10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -1.5999999999999996,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2.2,
        y: -17.400000000000002,
      },
    ],
  },
  {
    type: "pcb_via",
    x: 16,
    y: 3,
    from_layer: "top",
    to_layer: "bottom",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "pcb_via",
    x: 16,
    y: -6,
    from_layer: "bottom",
    to_layer: "top",
    hole_diameter: 0.2,
    outer_diameter: 0.4,
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_12",
    connected_source_port_ids: ["source_port_2", "source_port_24"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_12",
    schematic_trace_id: "schematic_trace_12",
    edges: [
      {
        from: {
          x: -3,
          y: -1.5,
        },
        to: {
          x: 1.6000000000000005,
          y: -1.5,
        },
      },
      {
        from: {
          x: 1.6000000000000005,
          y: -1.5,
        },
        to: {
          x: 1.6000000000000005,
          y: -1,
        },
      },
      {
        from: {
          x: 1.6000000000000005,
          y: -1,
        },
        to: {
          x: 3.3,
          y: -1,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_11",
    source_trace_id: "source_trace_12",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8.2,
        y: -5.000000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8,
        y: -5.200000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8,
        y: -5.199999999999999,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 8,
        y: -5.600000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 6,
        y: -7.600000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 6,
        y: -8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 5.6,
        y: -8.4,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 5.6,
        y: -8.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 4.800000000000001,
        y: -9.600000000000001,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 4.800000000000001,
        y: -10,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2,
        y: -16.8,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2.2,
        y: -17.400000000000002,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_13",
    connected_source_port_ids: ["source_port_13", "source_port_24"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_13",
    schematic_trace_id: "schematic_trace_13",
    edges: [
      {
        from: {
          x: 0.7,
          y: -1,
        },
        to: {
          x: 3.3,
          y: -1,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_12",
    source_trace_id: "source_trace_13",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2.2,
        y: -17.400000000000002,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: -2.2,
        y: -17.200000000000003,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 0,
        y: -15.000000000000002,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 0,
        y: -15,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 2,
        y: -15,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 3,
        y: -14,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 10,
        y: -14,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22,
        y: -2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.2,
        x: 22.8,
        y: -2,
      },
    ],
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_14",
    connected_source_port_ids: ["source_port_21", "source_port_23"],
  },
  {
    type: "schematic_trace",
    source_trace_id: "source_trace_14",
    schematic_trace_id: "schematic_trace_14",
    edges: [
      {
        from: {
          x: 2,
          y: -2.6,
        },
        to: {
          x: 2.9000000000000004,
          y: -2.6,
        },
      },
      {
        from: {
          x: 2.9000000000000004,
          y: -2.6,
        },
        to: {
          x: 2.9000000000000004,
          y: -1.6,
        },
      },
      {
        from: {
          x: 2.9000000000000004,
          y: -1.6,
        },
        to: {
          x: 3.3000000000000003,
          y: -1.6,
        },
      },
      {
        from: {
          x: 3.3000000000000003,
          y: -1.6,
        },
        to: {
          x: 3.3000000000000003,
          y: -1.5,
        },
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_13",
    source_trace_id: "source_trace_14",
    route: [
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -2.1999999999999993,
        y: -20,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -8,
        y: -20,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -8,
        y: -20,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -8,
        y: -24,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -8,
        y: -24.000000000000004,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -8.799999999999997,
        y: -24.000000000000004,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -9.2,
        y: -24.400000000000006,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -9.399999999999999,
        y: -24.400000000000006,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -12,
        y: -27.000000000000004,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -12.399999999999999,
        y: -27.000000000000004,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -29.6,
        y: -44.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -29.8,
        y: -44.2,
      },
      {
        route_type: "wire",
        layer: "top",
        width: 0.6,
        x: -30,
        y: -44.400000000000006,
      },
    ],
  },
]
